// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateAccount(arg1:string,arg2:number,arg3:number,arg4:any,arg5:string,arg6:string,arg7:number,arg8:Array<number>):Promise<main.Account>;

export function CreateGroup(arg1:string,arg2:string,arg3:string):Promise<main.Group>;

export function CreateIncome(arg1:number,arg2:number,arg3:string,arg4:string):Promise<main.Income>;

export function CreateIncomeSource(arg1:string,arg2:string,arg3:string):Promise<main.IncomeSource>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteGroup(arg1:number):Promise<void>;

export function DeleteIncome(arg1:number):Promise<void>;

export function DeleteIncomeSource(arg1:number):Promise<void>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetAvailableYears():Promise<Array<number>>;

export function GetGroups():Promise<Array<main.Group>>;

export function GetIncomeSources():Promise<Array<main.IncomeSource>>;

export function GetIncomes(arg1:number,arg2:number):Promise<Array<main.Income>>;

export function GetMonthSummary(arg1:number,arg2:number):Promise<main.MonthSummary>;

export function GetPayments(arg1:number,arg2:number):Promise<Array<main.Payment>>;

export function GetSuggestedPayment(arg1:number,arg2:number,arg3:number):Promise<number>;

export function GetYearSummary(arg1:number):Promise<main.YearSummary>;

export function PayAccount(arg1:main.PayAccountInput):Promise<main.Payment>;

export function UnpayAccount(arg1:number,arg2:number,arg3:number):Promise<void>;

export function UpdateAccount(arg1:number,arg2:string,arg3:number,arg4:number,arg5:any,arg6:boolean,arg7:string,arg8:string,arg9:number,arg10:Array<number>):Promise<main.Account>;

export function UpdateGroup(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<main.Group>;

export function UpdateIncome(arg1:number,arg2:number,arg3:number,arg4:string,arg5:string):Promise<main.Income>;

export function UpdateIncomeSource(arg1:number,arg2:string,arg3:string,arg4:string):Promise<main.IncomeSource>;
