// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2, arg3);
}

export function CreateIncome(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateIncome'](arg1, arg2, arg3, arg4);
}

export function CreateIncomeSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateIncomeSource'](arg1, arg2, arg3);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteIncome(arg1) {
  return window['go']['main']['App']['DeleteIncome'](arg1);
}

export function DeleteIncomeSource(arg1) {
  return window['go']['main']['App']['DeleteIncomeSource'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAvailableYears() {
  return window['go']['main']['App']['GetAvailableYears']();
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetIncomeSources() {
  return window['go']['main']['App']['GetIncomeSources']();
}

export function GetIncomes(arg1, arg2) {
  return window['go']['main']['App']['GetIncomes'](arg1, arg2);
}

export function GetMonthSummary(arg1, arg2) {
  return window['go']['main']['App']['GetMonthSummary'](arg1, arg2);
}

export function GetPayments(arg1, arg2) {
  return window['go']['main']['App']['GetPayments'](arg1, arg2);
}

export function GetSuggestedPayment(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSuggestedPayment'](arg1, arg2, arg3);
}

export function GetYearSummary(arg1) {
  return window['go']['main']['App']['GetYearSummary'](arg1);
}

export function PayAccount(arg1) {
  return window['go']['main']['App']['PayAccount'](arg1);
}

export function UnpayAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['UnpayAccount'](arg1, arg2, arg3);
}

export function UpdateAccount(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function UpdateGroup(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateIncome(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateIncome'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateIncomeSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateIncomeSource'](arg1, arg2, arg3, arg4);
}
